// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uwynicedvvigtacdfrxo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV3eW5pY2VkdnZpZ3RhY2RmcnhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwOTQ3OTAsImV4cCI6MjA2NjY3MDc5MH0.6m9Yk5vu0m1a2CTPW4WbrBzpWdgynpcb7iJxU25K5-g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);